services:
  password:
    image: password_app_prd
    container_name: password_app_prd
    build:
      context: .
      dockerfile: Dockerfile.password.PRD
    ports:
      - "6403:3000"
    environment:
      - TZ=America/Costa_Rica
    restart: unless-stopped
