services:
  password:
    image: password_app_dev
    container_name: password_app_dev
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.password.dev
    volumes:
      - ./password:/code/password
      - /code/password/node_modules
      - ./password_generator.py:/code/password_generator.py:ro
      - ./eff_short_wordlist_1.txt:/code/eff_short_wordlist_1.txt:ro
    ports:
      - "6403:3000"
      - "9229:9229"
    environment:
      - TZ=America/Costa_Rica
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
